# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    vlc \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Set environment variables for VLC
ENV VLC_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vlc/plugins

# Copy the current directory contents into the container at /app
COPY . /app

# Set the working directory
WORKDIR /app

# Expose port if necessary (e.g., for MySQL, but generally not needed here)

# Command to run the application
CMD ["python3", "annotation.py"]  
